config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :tax_calculations, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tax_calculations_controller.rb
class TaxCalculationsController < ApplicationController
    def new 

    end

    def create
        result = TaxCalculator.call(
            promo: params.fetch(:promo),
            subtotal: params.fetch(:subtotal).to_i,
            state: params.fetch(:state),
            tax_exempt: params[:tax_exempt].present?
        )

        if result.success?
            @subtotal = result.subtotal
            @total = result.total
            @promo_value = result.promo_value
            @taxes = result.taxes
        else 
            flash.notice = result.message
            render :new
        end  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServiceWorkshopDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tax_calculations/new.html.erb
<%= form_tag tax_calculations_path, method: :post do  %>
  <div style="display: block;">
    <%= label_tag :subtotal %>
    <%= number_field_tag :subtotal %>
  </div>
  <div style="display: block;">
    <%= label_tag :promo %>
    <%= text_field_tag :promo %>
  </div>
  <div style="display: block;">
    <%= label_tag :tax_exempt %>
    <%= check_box_tag :tax_exempt %>
  </div>
  <div style="display: block;">
    <%= label_tag :state %>
    <%= select_tag :state, options_for_select(StateTaxRates::ALL_RATES.keys) %>
  </div>
  <div style="display: block;">
    <%= label_tag :subtotal %>
    <%= number_field_tag :subtotal %>
  </div>
  <div style="display: block">
    <%= submit_tag "Submit" %>
  </div>
<% end %>